FROM python:3.10-slim-buster
WORKDIR /app
COPY ./requirements.txt /app
RUN pip install -r requirements.txt
COPY . .
CMD ["celery", "-A", "celeryapp_groups", "-A", "celeryapp_cmds", "flower", "--address=0.0.0.0", "--port=5555"]